### PR TITLE
Create keybase.txt

### PR DESCRIPTION
**Pull request by JonahAragon**
Proof of administration for https://keybase.io/jonaharagon

@Fusl I know you've already verified the domain via dns on keybase, which this won't affect, but if you want to verify the domain via http as well you can just append your proof to this file.

### CODE REVIEW

**Comment by JonahAragon** [comment]
Deploy preview for *opennic* ready!

Built with commit 38ffbba3ba103f2c510f8c50d43d73c92e91cb25

https://deploy-preview-32--opennic.netlify.com

**Comment by JonahAragon** [comment]
If anybody else is really administering/maintaining this website in the future they can append a Keybase proof to that document, like I mentioned you could. Multiple proofs can exist in that file. Check out keybase.io’s for example, that one contains verifications for ‘chris’ and ‘max’: https://keybase.io/.well-known/keybase.txt

And theoretically if I’m no longer managing this website, mine posted here can be removed and replaced in another PR by a new maintainer. 

It shouldn’t conflict with anyone else.

**Comment by JonahAragon** [comment]
I’m going to push this through for now since I don’t think the conflict you brought up will be an issue with how Keybase operates. I don’t think a subdomain system is necessary.

**Comment by Fusl** [comment]
:+1:

**Pull request merged**
