### PR TITLE
Force wrap the cryptocurrency addresses

### LINKED ISSUE #36: ETH and XMR addresses too wide for window
White-font cryptocurrency addresses create a seemingly blank section when scrolling to the side on devices where the window is too narrow to display the full text.

### PR DESCRIPTION
**Pull request by JonahAragon**
Fixes #36. Force wraps the cryptocurrency addresses so they fit in the window, as shown here in a mobile viewport. Is this a good solution? https://jda.mn/dhiz9

### CODE REVIEW

**Comment by JonahAragon** [comment]
Deploy preview for *opennic* ready!

Built with commit 8de5b5d1f95bd15d965d6a7049d483ecaa61fffe

https://deploy-preview-40--opennic.netlify.com

**Comment by Fusl** [comment]
Not to be a PITA but does anything speak against truncating the text and showing three dots at the end?
```
  text-overflow: ellipsis;
  /* Required for text-overflow to do anything */
  white-space: nowrap;
  overflow: hidden;
``

**Comment by JonahAragon** [comment]
@Fusl uh well if you want people to actually send you money they *probably* need the full address 😛

**Comment by JonahAragon** [comment]
(That's exactly how I copy things... maybe I need to be more efficient)

Thanks, pushing through.

**Pull request merged**
