### PR TITLE
Adding lang="en" attribute to html element

### PR DESCRIPTION
**Pull request by Fusl**

### CODE REVIEW

**Comment by JonahAragon** [comment]
Deploy preview ready!

Built with commit 1393bfe191bc79b4b97adbaef0ad384c098263a3

https://deploy-preview-17--opennic.netlify.com

**Comment by JonahAragon** [comment]
Should this be further changed to en-US? The page is generally written from an American perspective, which is fairly different from British English for example.

**Comment by Fusl** [comment]
`en-US` wouldn't be a valid ISO code to fix into the html-elements lang attribute.

**Comment by JonahAragon** [comment]
It isn't an ISO code yes, but BCP 47 and RFC 1766 seem to state that country/region subtags are accepted (and encouraged in situations where spelling and vocabulary differ by region), so `en-US` would be a valid code.

>    The syntax of this tag in RFC-822 EBNF is:
> 
>     Language-Tag = Primary-tag *( "-" Subtag )
>     Primary-tag = 1*8ALPHA
>     Subtag = 1*8ALPHA

> In the first subtag:
> 
>     -    All 2-letter codes are interpreted as ISO 3166 alpha-2
>          country codes denoting the area in which the language is
>          used.
([1766](https://tools.ietf.org/html/rfc1766))

If I'm reading this right and that is the case, then we should be using `en-US`, as from what I could gather, `en` defaults to `en-GB`, which is an entirely different set of spellings, etc.

**Comment by Fusl** [comment]
Looks like you're right, `en-US` is indeed a correct value for this attribute: https://stackoverflow.com/questions/31936783/which-language-attribute-is-correct

**Pull request merged**
